// AUTO-GENERATED from the live Acuity scheduler. Do not hand-edit.
// Source: https://braidsbykristian.as.me/schedule/b36fc416
// Regenerate: see docs/CONTENT.md ("Refreshing the catalog").
// Extracted: 47 services / 11 categories / 7 add-ons.

import type { RawAddon, RawCategory, RawService } from './schema'

export const rawCategories: RawCategory[] = [
  { slug: "knotless", name: "Knotless Braids", acuityName: "Knotless Styles", order: 1 },
  { slug: "bohemian", name: "Bohemian", acuityName: "Bohemian Styles", order: 2 },
  { slug: "twists", name: "Twists", acuityName: "Twist Styles", order: 3 },
  { slug: "bora-bora", name: "Bora Bora", acuityName: "Bora Bora Styles", order: 4 },
  { slug: "fulani", name: "Fulani", acuityName: "Fulani Styles", order: 5 },
  { slug: "cornrows", name: "Cornrows", acuityName: "Cornrow Styles", order: 6 },
  { slug: "locs", name: "Locs", acuityName: "Locs", order: 7 },
  { slug: "miracle-knot", name: "Miracle Knot", acuityName: "Miracle Knot", order: 8 },
  { slug: "natural-hair", name: "Natural Hair", acuityName: "Natural Hair", order: 9 },
  { slug: "lil-krownz", name: "Lil Krownz", acuityName: "Lil Krownz (ages 12 and under)", order: 10 },
  { slug: "touch-ups", name: "Touch-Ups & Removal", acuityName: "Touch Up’s & Removal", order: 11 },
]

export const rawAddons: RawAddon[] = [
  { id: 6039755, name: "Boho", price: 40, durationMinutes: 2 },
  { id: 6395509, name: "Butt Length", price: 30, durationMinutes: 1 },
  { id: 5777620, name: "Curly Ends", price: 0, durationMinutes: 0 },
  { id: 6039740, name: "Extra Boho", price: 10, durationMinutes: 1 },
  { id: 6880974, name: "Loc re twist", price: 125, durationMinutes: 60 },
  { id: 5777309, name: "Style", price: 30, durationMinutes: 10 },
  { id: 6395514, name: "Thigh length", price: 50, durationMinutes: 10 },
]

export const rawServices: RawService[] = [
  {
    id: 81229385,
    slug: "extra-small-bohemian-knotless",
    name: "Extra Small Bohemian Knotless",
    category: "bohemian",
    price: 265,
    priceMode: "fixed",
    durationMinutes: 540,
    size: "extra-small",
    notes: ["Please DO NOT book if you are not willing to sit for 8+ Hours"],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [6039740, 6395509, 6395514],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 75444431,
    slug: "small-bohemian-knotless",
    name: "Small Bohemian Knotless",
    category: "bohemian",
    price: 180,
    priceMode: "fixed",
    durationMinutes: 420,
    size: "small",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [6039740, 6395509, 6395514],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 78312091,
    slug: "small-bohemian-knotless-bob",
    name: "Small Bohemian Knotless Bob",
    category: "bohemian",
    price: 175,
    priceMode: "fixed",
    durationMinutes: 420,
    size: "small",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [6039740],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 75534721,
    slug: "medium-bohemian-knotless",
    name: "Medium Bohemian Knotless",
    category: "bohemian",
    price: 165,
    priceMode: "fixed",
    durationMinutes: 420,
    size: "medium",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [6039740, 6395509, 6395514],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 78312145,
    slug: "medium-bohemian-knotless-bob",
    name: "Medium Bohemian Knotless Bob",
    category: "bohemian",
    price: 160,
    priceMode: "fixed",
    durationMinutes: 420,
    size: "medium",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [6039740],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 75534787,
    slug: "large-bohemian-knotless",
    name: "Large Bohemian Knotless",
    category: "bohemian",
    price: 150,
    priceMode: "fixed",
    durationMinutes: 360,
    size: "large",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [6039740, 6395509, 6395514],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 85733984,
    slug: "extra-small-bora-bora",
    name: "Extra Small Bora Bora",
    category: "bora-bora",
    price: 300,
    priceMode: "fixed",
    durationMinutes: 570,
    size: "extra-small",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [6395509, 6395514],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 85733894,
    slug: "small-bora-bora",
    name: "Small Bora Bora",
    category: "bora-bora",
    price: 250,
    priceMode: "fixed",
    durationMinutes: 540,
    size: "small",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [6395509, 6395514, 6880974],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 79817117,
    slug: "4-plus-straight-back-braids",
    name: "4+ Straight Back Braids",
    category: "cornrows",
    price: 155,
    priceMode: "fixed",
    durationMinutes: 180,
    size: null,
    notes: [],
    hairProvidedBy: "unspecified",
    hairEvidence: "Not stated on the Acuity booking.",
    addonIds: [6039740, 6039755, 6395509, 6395514],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 79817014,
    slug: "2-to-4-straight-back-braids",
    name: "2 to 4 Straight Back Braids",
    category: "cornrows",
    price: 135,
    priceMode: "fixed",
    durationMinutes: 180,
    size: null,
    notes: [],
    hairProvidedBy: "unspecified",
    hairEvidence: "Not stated on the Acuity booking.",
    addonIds: [6039740, 6039755, 6395509, 6395514],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 75584906,
    slug: "freestyle",
    name: "Freestyle",
    category: "cornrows",
    price: 0,
    priceMode: "quoted",
    durationMinutes: 360,
    size: null,
    notes: ["When booking this appointment, please contact me with a description of the desired style."],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [6039740, 6039755, 6395509, 6395514],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 95079864,
    slug: "fulani-quickweave",
    name: "Fulani QuickWeave",
    category: "fulani",
    price: 180,
    priceMode: "fixed",
    durationMinutes: 240,
    size: null,
    notes: ["Bundles are not included", "For a full look in the back, you will need 2-3 bundles", "When booking this appoint please contact me with a description of desired style for the front braids."],
    hairProvidedBy: "client",
    hairEvidence: "Stated on the Acuity booking: hair/bundles are not included.",
    addonIds: [],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 79816558,
    slug: "bohemian-fulani-knotless",
    name: "Bohemian Fulani Knotless",
    category: "fulani",
    price: 180,
    priceMode: "fixed",
    durationMinutes: 420,
    size: null,
    notes: [],
    hairProvidedBy: "unspecified",
    hairEvidence: "Not stated on the Acuity booking.",
    addonIds: [6039740, 6395509, 6395514],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 79812371,
    slug: "basic-fulani-knotless",
    name: "Basic Fulani Knotless",
    category: "fulani",
    price: 165,
    priceMode: "fixed",
    durationMinutes: 360,
    size: null,
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [6395509, 6395514],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 79816455,
    slug: "flip-over-fulani-knotless",
    name: "Flip Over Fulani Knotless",
    category: "fulani",
    price: 165,
    priceMode: "fixed",
    durationMinutes: 360,
    size: null,
    notes: [],
    hairProvidedBy: "unspecified",
    hairEvidence: "Not stated on the Acuity booking.",
    addonIds: [6039740, 6039755, 6395509, 6395514],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 75443558,
    slug: "small-knotless",
    name: "Small Knotless",
    category: "knotless",
    price: 170,
    priceMode: "fixed",
    durationMinutes: 420,
    size: "small",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [5777620, 6395509, 6395514],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 78279969,
    slug: "small-knotless-bob",
    name: "Small Knotless Bob",
    category: "knotless",
    price: 165,
    priceMode: "fixed",
    durationMinutes: 360,
    size: "small",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 75443741,
    slug: "medium-knotless",
    name: "Medium Knotless",
    category: "knotless",
    price: 155,
    priceMode: "fixed",
    durationMinutes: 360,
    size: "medium",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [5777620, 6395509, 6395514],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 78280112,
    slug: "medium-knotless-bob",
    name: "Medium Knotless Bob",
    category: "knotless",
    price: 150,
    priceMode: "fixed",
    durationMinutes: 360,
    size: "medium",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 75443395,
    slug: "large-knotless",
    name: "Large Knotless",
    category: "knotless",
    price: 140,
    priceMode: "fixed",
    durationMinutes: 360,
    size: "large",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [5777620, 6395509, 6395514],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 81229656,
    slug: "small-medium-large-bohemian-knotless-braids",
    name: "Small/Medium/Large Bohemian Knotless Braids",
    category: "lil-krownz",
    price: 155,
    priceMode: "fixed",
    durationMinutes: 420,
    size: "choice",
    notes: ["Length of style will not be longer than lower back"],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [6039740],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 81229169,
    slug: "small-medium-large-knotless-braids",
    name: "Small/Medium/Large Knotless Braids",
    category: "lil-krownz",
    price: 150,
    priceMode: "fixed",
    durationMinutes: 360,
    size: "choice",
    notes: ["Length of style will not be longer than lower back"],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 95689256,
    slug: "lil-krownz-back-2-school-special",
    name: "Lil Krownz Back 2 School Special",
    category: "lil-krownz",
    price: 100,
    priceMode: "fixed",
    durationMinutes: 360,
    size: null,
    notes: ["All Lil Krownz Styles | $100", "Please note: A $25 non-refundable deposit is required and is NOT included in the $100 price"],
    hairProvidedBy: "unspecified",
    hairEvidence: "Not stated on the Acuity booking.",
    addonIds: [],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 81146301,
    slug: "braided-ponytail",
    name: "Braided Ponytail",
    category: "lil-krownz",
    price: 85,
    priceMode: "fixed",
    durationMinutes: 360,
    size: null,
    notes: ["Choice of either one or two ponytails"],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 82901123,
    slug: "small-medium-soft-locs",
    name: "Small–Medium Soft Locs",
    category: "locs",
    price: 175,
    priceMode: "fixed",
    durationMinutes: 480,
    size: "small-medium",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [6039740, 6039755, 6395509, 6395514],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 75445540,
    slug: "loc-re-twist",
    name: "Loc Re-Twist",
    category: "locs",
    price: 130,
    priceMode: "fixed",
    durationMinutes: 240,
    size: null,
    notes: [],
    hairProvidedBy: "unspecified",
    hairEvidence: "Not stated on the Acuity booking.",
    addonIds: [5777309],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 95155896,
    slug: "small-miracle-knot",
    name: "Small Miracle Knot",
    category: "miracle-knot",
    price: 150,
    priceMode: "fixed",
    durationMinutes: 360,
    size: "small",
    notes: ["Hair is not included", "You will need 3-4 bundles of 100% Human Hair feather crochet bundles for a full look"],
    hairProvidedBy: "client",
    hairEvidence: "Stated on the Acuity booking: hair/bundles are not included.",
    addonIds: [],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 95156030,
    slug: "medium-miracle-knot",
    name: "Medium Miracle Knot",
    category: "miracle-knot",
    price: 140,
    priceMode: "fixed",
    durationMinutes: 300,
    size: "medium",
    notes: ["Hair is not included", "You will need 3-4 bundles of 100% Human Hair feather crochet bundles for a full look"],
    hairProvidedBy: "client",
    hairEvidence: "Stated on the Acuity booking: hair/bundles are not included.",
    addonIds: [],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 94519886,
    slug: "natural-hair-cornrow-freestyle",
    name: "Natural Hair Cornrow Freestyle",
    category: "natural-hair",
    price: 130,
    priceMode: "fixed",
    durationMinutes: 300,
    size: null,
    notes: ["When booking this appointment, please contact me with a description of the desired style."],
    hairProvidedBy: "not-applicable",
    hairEvidence: "Natural Hair services are styled on your own hair; no added braiding hair.",
    addonIds: [],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 75445496,
    slug: "natural-hair-box-braids",
    name: "Natural Hair Box Braids",
    category: "natural-hair",
    price: 125,
    priceMode: "fixed",
    durationMinutes: 360,
    size: null,
    notes: [],
    hairProvidedBy: "not-applicable",
    hairEvidence: "Natural Hair services are styled on your own hair; no added braiding hair.",
    addonIds: [],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 75445451,
    slug: "natural-hair-2-strand-twist",
    name: "Natural Hair 2 Strand Twist",
    category: "natural-hair",
    price: 125,
    priceMode: "fixed",
    durationMinutes: 360,
    size: null,
    notes: [],
    hairProvidedBy: "not-applicable",
    hairEvidence: "Natural Hair services are styled on your own hair; no added braiding hair.",
    addonIds: [],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 94520133,
    slug: "natural-hair-4-plus-straight-back-cornrow",
    name: "Natural Hair 4+ Straight Back Cornrow",
    category: "natural-hair",
    price: 100,
    priceMode: "fixed",
    durationMinutes: 180,
    size: null,
    notes: [],
    hairProvidedBy: "not-applicable",
    hairEvidence: "Natural Hair services are styled on your own hair; no added braiding hair.",
    addonIds: [],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 94520066,
    slug: "natural-hair-2-to-4-straight-back-cornrow",
    name: "Natural Hair 2 to 4 Straight Back Cornrow",
    category: "natural-hair",
    price: 75,
    priceMode: "fixed",
    durationMinutes: 180,
    size: null,
    notes: [],
    hairProvidedBy: "not-applicable",
    hairEvidence: "Natural Hair services are styled on your own hair; no added braiding hair.",
    addonIds: [],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 85336258,
    slug: "small-bohemian-touch-up",
    name: "Small Bohemian Touch Up",
    category: "touch-ups",
    price: 135,
    priceMode: "fixed",
    durationMinutes: 300,
    size: "small",
    notes: ["This service is only for the perimeter of the head ( 2-3 rows)", "Service includes a take down & wash"],
    hairProvidedBy: "unspecified",
    hairEvidence: "Not stated on the Acuity booking.",
    addonIds: [],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 78907534,
    slug: "small-knotless-touch-up",
    name: "Small Knotless Touch Up",
    category: "touch-ups",
    price: 130,
    priceMode: "fixed",
    durationMinutes: 300,
    size: "small",
    notes: ["This service is only for the perimeter of the head ( 2-3 rows)", "Service includes a take down & wash"],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [5777620, 6039740, 6395509, 6395514],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 85336371,
    slug: "medium-bohemian-touch-up",
    name: "Medium Bohemian Touch Up",
    category: "touch-ups",
    price: 130,
    priceMode: "fixed",
    durationMinutes: 300,
    size: "medium",
    notes: ["This service is only for the perimeter of the head ( 2-3 rows)", "Service includes a take down & wash"],
    hairProvidedBy: "unspecified",
    hairEvidence: "Not stated on the Acuity booking.",
    addonIds: [],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 85335960,
    slug: "medium-knotless-touch-up",
    name: "Medium Knotless Touch Up",
    category: "touch-ups",
    price: 125,
    priceMode: "fixed",
    durationMinutes: 300,
    size: "medium",
    notes: ["This service is only for the perimeter of the head ( 2-3 rows)", "Service includes a take down & wash"],
    hairProvidedBy: "unspecified",
    hairEvidence: "Not stated on the Acuity booking.",
    addonIds: [],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 85336401,
    slug: "large-bohemian-touch-up",
    name: "Large Bohemian Touch Up",
    category: "touch-ups",
    price: 125,
    priceMode: "fixed",
    durationMinutes: 300,
    size: "large",
    notes: ["This service is only for the perimeter of the head ( 2-3 rows)", "Service includes a take down & wash"],
    hairProvidedBy: "unspecified",
    hairEvidence: "Not stated on the Acuity booking.",
    addonIds: [],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 81228932,
    slug: "braid-removal",
    name: "Braid Removal",
    category: "touch-ups",
    price: 125,
    priceMode: "fixed",
    durationMinutes: 210,
    size: null,
    notes: ["This service is for Braid Removal ONLY"],
    hairProvidedBy: "unspecified",
    hairEvidence: "Not stated on the Acuity booking.",
    addonIds: [],
    requiresHairColorForm: false,
    calendar: "Sydney Verdun",
  },
  {
    id: 85336111,
    slug: "large-knotless-touch-up",
    name: "Large Knotless Touch Up",
    category: "touch-ups",
    price: 120,
    priceMode: "fixed",
    durationMinutes: 300,
    size: "large",
    notes: ["This service is only for the perimeter of the head ( 2-3 rows)", "Service includes a take down & wash"],
    hairProvidedBy: "unspecified",
    hairEvidence: "Not stated on the Acuity booking.",
    addonIds: [],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 75444654,
    slug: "small-island-twist",
    name: "Small Island Twist",
    category: "twists",
    price: 180,
    priceMode: "fixed",
    durationMinutes: 420,
    size: "small",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [6039740, 6395509, 6395514],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 85498981,
    slug: "small-senegalese-twist",
    name: "Small Senegalese Twist",
    category: "twists",
    price: 170,
    priceMode: "fixed",
    durationMinutes: 420,
    size: "small",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [5777620, 6395509, 6395514],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 83205468,
    slug: "small-mini-twist",
    name: "Small Mini Twist",
    category: "twists",
    price: 165,
    priceMode: "fixed",
    durationMinutes: 420,
    size: "small",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [6039740, 6039755, 6395509, 6395514],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 79568112,
    slug: "medium-island-twist",
    name: "Medium Island Twist",
    category: "twists",
    price: 165,
    priceMode: "fixed",
    durationMinutes: 420,
    size: "medium",
    notes: [],
    hairProvidedBy: "unspecified",
    hairEvidence: "Not stated on the Acuity booking.",
    addonIds: [6039740, 6395509, 6395514],
    requiresHairColorForm: false,
    calendar: "Kristian Pete",
  },
  {
    id: 85499038,
    slug: "medium-senegalese-twist",
    name: "Medium Senegalese Twist",
    category: "twists",
    price: 155,
    priceMode: "fixed",
    durationMinutes: 420,
    size: "medium",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [5777620, 6395509, 6395514],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 89111141,
    slug: "large-mini-twist",
    name: "Large Mini Twist",
    category: "twists",
    price: 155,
    priceMode: "fixed",
    durationMinutes: 360,
    size: "large",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [6039755, 6395509, 6395514],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
  {
    id: 83205519,
    slug: "medium-mini-twist",
    name: "Medium Mini Twist",
    category: "twists",
    price: 150,
    priceMode: "fixed",
    durationMinutes: 420,
    size: "medium",
    notes: [],
    hairProvidedBy: "client",
    hairEvidence: "Acuity requires the \"Braiding Hair Color\" form for this service, which asks for the colour of the hair you will be providing.",
    addonIds: [6039740, 6039755, 6395509, 6395514],
    requiresHairColorForm: true,
    calendar: "Kristian Pete",
  },
]
